# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  mail:
    host: smtp.163.com
    username: 18040520017@163.com
    password: PILNGVMJPEXNVRDA
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/chatai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liUpnU7nof5IQO9G
            client-secret: 5c4bed87b958677d922bdad3a82f90f0da4c3246
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: GitHub
          gitee:
            client-id: 0bb7105d92911c89607f9d52b3abe6d6b20a6f0564cd838270aaa8db11b141d2
            client-secret: 9e1638724234086e1cb7b78935512cccd0b2bc1b97005dce4d945286b1097694
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/api/auth/gitee/callback'
            client-name: Gitee
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: name
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
Account:
  default_token: 50.0
#支付宝
alipay:
  appId: 9021000139678281
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRCSlSVHStzDD1Fz2zy1/nkzGJjlysYOXCdoxbc/CQb0A/UarybZvg3FM0qTpoLETAj5uWK409xs0phECXWYTNwgOBJ8FxaPUui48qVmQ2o79lG6lIXcJFwJgRsouCFJj1WSfzP2WV/AxK4W/pwewE2Nn9z44+KqVUSPK2wG6oJeS0SZpGA8fI1t+7O26hAC4TB4AvfvV5jvgkhbAwYhUCBZl3g35ouymGDcY2KqpeQdNEhe5PpfHvGcxUm01QXTch8xKndmHGdr3Rm+uPvHXlMYsDtTuPjkRHjzu+Y5/12OE3joKJnTA90Ur5u/Funnx386jZJ2YqohxrEevBO8jTAgMBAAECggEAHicScSxfyZYvA3VefZeli6Z9YQS43ZmTitdMnOLAu7Z1W/SlnpsNEjWcEtGv8+JoNMRma1UImzROiPgW2aBhzMkuI1bZj7Nrbc7T59BoKzfl3aZfjkz3y7qboupEuLmBh1iOxrKCcykggRzXQHjxkZxnza2t+9yv3JMB6t6c4tYVxDQtsVZ/cj0EZFXWRUv9sKu1NFTLIdH/67fTTeXPKdQCeSC7qOcwWnAeGs/YVgoninNWbwoFQXqADkOu+ohrTRTWIe+ERCgXWE1gSnU/D0KIhzx9x9+ecBG56fzOBLm9eZZVAhSU3TgOFNX5zvbNsJScNwZlKZCqLIpZsUUi6QKBgQDIeUBlg8SwY0tQrormGL3v0KVcqzfIcSmy6B4dkEfO4P+0F0/eua2C6kNH327WQgxAulHvOrTo9R9u0KFA7Q+XjYlH8wYQKpceZacQEd8X9ED31FWtuSzOvUkTO3A+cbAEohh+IlalcJytlEPEk/HUzbDnXSVQC53DeBO7Ka7GPwKBgQC5NQsWQSmZ0OWQo9e8DJWvc1cJawaSFlWkk5vrIHK2azeuYLlPuYWJ3lBfqF9wt/X19bdLykjK+3K3sDX/3tCHhTqqPeMFk3MIIBd+Prk+qrIC9w/x3PfXItGcRp/h7dVcD5yi3K1IDEzsEWM7b4Ji3xIr2xGosd/+48OVI5agbQKBgHRaU3LX0I+jgbH5K+qyT4LhsSggw8aVT2Nj7x6vf83lruNCaHvXfoouFxCe8IBwYxYqTaWwiBFxO2YgtoatUFBguF3HAizd20msLBNanAYWIKL2XSfwAr6XA9OiutmzODroLZj/qxRoULc6Bz8PstsU6ujNmftkUpOBnMoTPjoXAoGAJDN0CVOPWBt248DCyGUFVRgMaTDcRe3Lq7GWhmz/PxzR82nAjw7KRVqJB0mX7iZnEz6GJ3BQrixcDf+JbowU4ohuIRybpVle4LW1Id4Mw20GAoJcQYBZiVmq8wry8WxVifsbONI9pJmS54m2hcWUDNNhb+UQHJM4H1BRyHL+XDkCgYEAgyG/+zDWphC+Z0KftcSk1e3vzncaaRcJgFQ6UNHsiUCD1BaQboal2maBmrm3mJiIPfVeiuB4ov72E38V5zfBhmFnSVl+DG+rx1xkt2xgvIzbaOjuy1QLXmSytk2lKmv3uVgm86RVcic0Bb22FLoGXSAUHFbvXYHgP9Qkh/4ZYQc=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsakkaFCf3+hASWAnUukctYC+vxL88Usvuosj3LfSZGt/SF24FjY0CISmx3D8qkqrcJCIDjNawgCuQyKl13+td+xNsBn+YAcJJyl9gVC0vawrAw3uMIIusDydFLzTCrHpvlEKvZYG0e004HDwGUSIbei7B4MvEeZI4itLoujke7PGNerOXubAoHL/gYHUE9qs5Pzj3ToDTzWtBmdq2yvzKxJgP1CZmV9vgfTvA4OVMu9IrWBx0KTL1E/sBdazI1FRZ7yIge7WafGRtcahkU8+eHW9ZImn21tQwBydqIl7FUbP/6rsOFHfyFwhrF+WgCCtmJG4JLBeljnCrC/wFNa8iQIDAQAB
  notifyUrl:  https://supz.mynatapp.cc/alipay/notify
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  #回调地址（支付完返回的地址）
  returnUrl: http://127.0.0.1:5173/charge
#OpenKey
OpenKey:
  web_server: https://billing.openkey.cloud/api/token
  gpt_server: https://openkey.cloud/v1/chat/completions
#微信
WeiXin:
  appid: wx5963483aaf4a6422
  app_secret: c190cdfbaa8220cc0565df52da449dfb
  login:
    access_token_url: https://api.weixin.qq.com/sns/oauth2/access_token
    get_user_info_url: https://api.weixin.qq.com/sns/userinfo



